In [1]:
from sklearn import datasets, svm
iris = datasets.load_iris()

In [2]:
import pandas as pd
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[48:53]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   

        flower  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor  
52  versicolor

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.3)

In [9]:
model = svm.SVC(kernel = 'rbf', C = 30, gamma = 'auto')              # Here c is Capital
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9555555555555556

In [ ]:
# If u run above code again, it will run and show the different accuracies

### Cross validation

### 1.

In [10]:
from sklearn.model_selection import cross_val_score

In [12]:
cross_val_score(svm.SVC(kernel = 'linear', C = 10, gamma = 'auto'), iris.data, iris.target, cv=5) # cv=5 means 5 folds

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

If we give c = 5 instead of C = 5 , it shows error

In [13]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 10, gamma = 'auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [14]:
cross_val_score(svm.SVC(kernel = 'linear', C = 20, gamma = 'auto'), iris.data, iris.target, cv=5) 

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [16]:
# This method is mannual and repetative that there are many values u have to supply (kernel and C)

### 2. Now we will do same thing by using for loop

In [18]:
import numpy as np
kernel = ['rbf','linear']
C = [1,10,20]
avg_score = {}
for kval in kernel:
    for cval in C:
        cv_score = cross_val_score(svm.SVC(kernel=kval, C = cval, gamma = 'auto'), iris.data, iris.target, cv = 5)
        avg_score[kval + '_' + str(cval)] = np.average(cv_score)
avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

### 3. sklearn provides API called grid search CV, which will do exact same thing as above.

In [21]:
from sklearn.model_selection import GridSearchCV
# Now we will define our classifier clf
# 11st parameter is Gamma, 2nd parameter is parameter grid C

clf = GridSearchCV(svm.SVC(gamma = 'auto'),{
    'C':[1,10,20],
    'kernel': ['rbf', 'linear']
}, cv=5, return_train_score=False)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00022206, 0.        , 0.00159688, 0.        , 0.0015955 ,
        0.        ]),
 'std_fit_time': array([0.00044413, 0.        , 0.00319376, 0.        , 0.00319099,
        0.        ]),
 'mean_score_time': array([0.00118356, 0.0016191 , 0.00161242, 0.0016118 , 0.        ,
        0.        ]),
 'std_score_time': array([0.00177004, 0.0032382 , 0.00322485, 0.00322361, 0.        ,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [ ]:
CV_RESULTS_ are not easy to view, it can be imported to the pandas dataframe

In [23]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.000222      0.000444         0.001184        0.001770       1   
1       0.000000      0.000000         0.001619        0.003238       1   
2       0.001597      0.003194         0.001612        0.003225      10   
3       0.000000      0.000000         0.001612        0.003224      10   
4       0.001595      0.003191         0.000000        0.000000      20   
5       0.000000      0.000000         0.000000        0.000000      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [24]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [25]:
# To check what are the properties or operations we can perform on the classifier, we will use
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_

In [27]:
# Let us try best score
clf.best_score_                    # If u pass best_score it will show an error

0.9800000000000001

In [28]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

### One issue may happen with gridsearchCV is that computation cost when the data set is too big
 To tackle this computation problem, in sklearn there is class - randomised search cv

In [36]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma = 'auto'), {
    'C': [1,10,20],
    'kernel': ['rbf', 'linear']
}, cv =5,
    return_train_score=False,
    n_iter=2                            # Try out only 2 combinations
)

rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]    # If we run it again it will change

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      20       linear         0.966667